name: Clang-format-check

on:
  push:
    branches: [ feature/github_actions ]
  pull_request:
    branches: [ feature/github_actions ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install clang
        # run:  sudo apt install clang-format
        run: |
          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-16 main" | sudo tee -a /etc/apt/sources.list.d/clang.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install clang-format-16
          sudo ln -s /usr/lib/llvm-16/bin/clang-format /usr/local/bin/clang-format
          clang-format --version

      - name: clang format check
        run: bash script/clang-format/run-style-check-diff.sh